name: UI Tests on BrowserStack

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.9.6'

    - name: Run tests on BrowserStack
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        mvn clean test -Dbrowser=chrome -DgridUrl=https://${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: browserstack-test-output
        path: test-output/**
