name: UI Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run tests (local Chrome)
        run: mvn clean test -Dbrowser=chrome

      - uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output/**
