name: UI Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.9.6'

    - name: Run tests (local Chrome)
      run: mvn clean test -Dbrowser=chrome

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-output
        path: test-output/**
